### PR TITLE
PyPeMicro 0.1.7 released with BSD support out of the box.

### PR DESCRIPTION
**Pull request by cederom**
Signed-off-by: Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>

### CODE REVIEW

**Comment by cederom** [comment]
Thank you @Gargy007 probably we need a release here as well? :-)

**Comment by Gargy007** [comment]
HI,
 yes you absolutely right, but this package is managed by Chris Reed.

Give him one / two day to update :-)
Petr

po 2. 8. 2021 v 12:54 odesílatel Tomasz CEDRO ***@***.***>
napsal:

**Comment by cederom** [comment]
Awsome :-) Thank you @Gargy007 :-) Waiting for @flit :-)

**Comment by flit** [comment]
Done! [v1.0.6](https://github.com/pyocd/pyocd-pemicro/releases/tag/v1.0.6)

**Comment by cederom** [comment]
TANK U @flit =)

**Pull request merged**
